name: Auto release

on: [push]

jobs:

  build-win:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.3.2
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
            
      - name: Compile
        id: compile2
        uses: rust-build/rust-build.action@v1.3.2
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile2.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile2.outputs.BUILT_CHECKSUM }}
            
      - name: Upload
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
            ${{ steps.compile.outputs2.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs2.BUILT_CHECKSUM }}
